package com.jaidev.seeaplayer.dataClass

enum class Platform {
    YOUTUBE, FACEBOOK, INSTAGRAM, TWITTER, VIMEO, DAILYMOTION, TIKTOK, TWITCH, REDDIT, PINTEREST,
    LINKEDIN, SNAPCHAT, WHATSAPP, TELEGRAM, WEIBO, TUMBLR, VINE, SOUNDCLOUD, MIXCLOUD, VK, UNKNOWN
}
